# Generated by Django 5.1.1 on 2024-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zajelgroup',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
